export const UPDATE_USERNAME: string = 'UPDATE_USERNAME';

export const POPULATE_PORTFOLIO: string = 'POPULATE_PORTFOLIO';

export const ADD_TO_PORTFOLIO: string = 'ADD_TO_PORTFOLIO';

export const DELETE_FROM_PORTFOLIO: string = 'DELETE_FROM_PORTFOLIO';

export const POPULATE_LEADERBOARD: string = 'POPULATE_LEADERBOARD';

export const UPDATE_BALANCE: string = 'UPDATE_BALANCE';

export const UPDATE_CURRENT_NFT: string = 'UPDATE_CURRENT_NFT';
